### ISSUE TITLE
Question: how to use own language with functionList

### ISSUE THREAD

**Issue by MaDill** [dail8859/ScintilluaPlusPlus#12]
How can I use the own syntax highlighting with the functionList.xml from N++? I tried to write the name what is displayed in the lower left corner of the status bar, but it does not work. What LangID or userDefinedLangName is needed?

As a workaround I create a user defined language with the needed extensions and setup this in the functionList.xml.

But somehow this is not working anymore with version 1.2

My N++ version is 7.4.1 32bit

**Comment by dail8859** [comment]
The way Scintillua++ works is a bit different from other external lexers and UDLs...so it some cases it probably won't play nice with some of Notepad++'s features. 

> What LangID or userDefinedLangName is needed?

Technically the lexer that is used is only known simply as `lpeg` regardless of what file is being highlighted. But I don't think Notepad++ would recognize that if you used it, because the way the lexer is set bypasses Notepad++'s mechanisms for setting it.

> But somehow this is not working anymore with version 1.2

If I had to guess it is probably due to f83b9afc6339f9295e9db1a20e098434131a3712. There is a bit of fighting that goes on between Notepad++ and Scintillua++ on syntax highlighting. This is because any time the user would switch to a file, Notepad++ would first lex it, and then Scintillua++ would. This commit tricks Notepad++ into thinking it never needs to do its own syntax highlighting on the file by telling it is a plain text file.
