### ISSUE TITLE
Block comment not working

### ISSUE THREAD

**Issue by royaction** [dail8859/ScintilluaPlusPlus#13]
This is a great plugin, but unfortunately the "block comment"-function is not working. It's the same like opening a file without extension - if notepad doesnt know the extension you can't block-comment.  Is there a workaround for this? I have not found a Notification callback for "Block comment insert" but maybe there is another way? 

Or would it be possible to add this function to scintillua++ ... like defining the comment-chars or something? I have no experience with lua or scintilla - i'm a web developer and i just want to highlight my scss-files in a better way then with the user defined languages. Sorry for my strange english ... i'm from germany.

Keep up the good work and best regards

**Comment by dail8859** [comment]
>  Is there a workaround for this?

No easy ones I can think of. There are a few areas that would need addressed:

1. Scintillua++ does not have a way to define comment characters. It does know how to highlight comments, but as for some way to say e.g. language "x" uses "//" to start a comment...there is nothing in there like that. Would not be that hard to solve though.
2. There's no direct way to hook into Notepad++'s logic of doing block comments. You can't tell it what characters to use, etc. Under normal circumstances Notepad++ "knows" what the language is and what comment characters are used for that language, and just does it when the command is ran.

One possibility would be to *rewrite* the logic that Notepad++ uses to do the comment blocks. But this could get a bit messy because there is no good way to override or replace Notepad++'s functionality when doing comments.
