### ISSUE TITLE
do not deliver Scintillua++.ini in the zip file

### ISSUE THREAD

**Issue by MaDill** [dail8859/ScintilluaPlusPlus#9]
When the user make changes in the ini file, it would be good, if the ini file is not part of the update.

Maybe a template could be put in the zip file and the plugin detect if the ini files is not in the config folder and create it by itself with the default values. Then it will be not overwritten when it is already there.

Thanks for the nice plugin. It's much easier to create own syntax highlighting in this way.

**Comment by dail8859** [comment]
Yeah this is the biggest thing I want to solve before putting this plugin in the Plugin Manager and had much the same idea as you. My only concern is if new lexers are added then the user would have to manually update their ini file if they wanted to use those new lexers. This probably is not a big deal because I think new lexers are not added too frequently to Scintillua.
